main: com.struckplayz.ulpl.UnlimitedPlugins
name: UnlimitedPlugins
author: Struck713
version: 1.3

commands:
    unlimitedplugins:
        aliases: [ulpl]
        description: Main UnlimitedPlugins command.
        usage: /<command> <enable/disable> <plugin>